package br.com.munif.learn.phd.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConjuntoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConjuntoAllPropertiesEquals(Conjunto expected, Conjunto actual) {
        assertConjuntoAutoGeneratedPropertiesEquals(expected, actual);
        assertConjuntoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConjuntoAllUpdatablePropertiesEquals(Conjunto expected, Conjunto actual) {
        assertConjuntoUpdatableFieldsEquals(expected, actual);
        assertConjuntoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConjuntoAutoGeneratedPropertiesEquals(Conjunto expected, Conjunto actual) {
        assertThat(expected)
            .as("Verify Conjunto auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConjuntoUpdatableFieldsEquals(Conjunto expected, Conjunto actual) {
        assertThat(expected)
            .as("Verify Conjunto relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConjuntoUpdatableRelationshipsEquals(Conjunto expected, Conjunto actual) {
        assertThat(expected)
            .as("Verify Conjunto relationships")
            .satisfies(e -> assertThat(e.getDataset()).as("check dataset").isEqualTo(actual.getDataset()));
    }
}
