package br.com.munif.learn.phd.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EtiquetaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaAllPropertiesEquals(Etiqueta expected, Etiqueta actual) {
        assertEtiquetaAutoGeneratedPropertiesEquals(expected, actual);
        assertEtiquetaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaAllUpdatablePropertiesEquals(Etiqueta expected, Etiqueta actual) {
        assertEtiquetaUpdatableFieldsEquals(expected, actual);
        assertEtiquetaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaAutoGeneratedPropertiesEquals(Etiqueta expected, Etiqueta actual) {
        assertThat(expected)
            .as("Verify Etiqueta auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaUpdatableFieldsEquals(Etiqueta expected, Etiqueta actual) {
        assertThat(expected)
            .as("Verify Etiqueta relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaUpdatableRelationshipsEquals(Etiqueta expected, Etiqueta actual) {
        assertThat(expected)
            .as("Verify Etiqueta relationships")
            .satisfies(e -> assertThat(e.getDataset()).as("check dataset").isEqualTo(actual.getDataset()));
    }
}
