package br.com.munif.learn.phd.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EtiquetagemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetagemAllPropertiesEquals(Etiquetagem expected, Etiquetagem actual) {
        assertEtiquetagemAutoGeneratedPropertiesEquals(expected, actual);
        assertEtiquetagemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetagemAllUpdatablePropertiesEquals(Etiquetagem expected, Etiquetagem actual) {
        assertEtiquetagemUpdatableFieldsEquals(expected, actual);
        assertEtiquetagemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetagemAutoGeneratedPropertiesEquals(Etiquetagem expected, Etiquetagem actual) {
        assertThat(expected)
            .as("Verify Etiquetagem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetagemUpdatableFieldsEquals(Etiquetagem expected, Etiquetagem actual) {
        assertThat(expected)
            .as("Verify Etiquetagem relevant properties")
            .satisfies(e -> assertThat(e.getX()).as("check x").isEqualTo(actual.getX()))
            .satisfies(e -> assertThat(e.getY()).as("check y").isEqualTo(actual.getY()))
            .satisfies(e -> assertThat(e.getLargura()).as("check largura").isEqualTo(actual.getLargura()))
            .satisfies(e -> assertThat(e.getAltura()).as("check altura").isEqualTo(actual.getAltura()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetagemUpdatableRelationshipsEquals(Etiquetagem expected, Etiquetagem actual) {
        assertThat(expected)
            .as("Verify Etiquetagem relationships")
            .satisfies(e -> assertThat(e.getEtiqueta()).as("check etiqueta").isEqualTo(actual.getEtiqueta()))
            .satisfies(e -> assertThat(e.getImagem()).as("check imagem").isEqualTo(actual.getImagem()));
    }
}
